backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Template Key", name: "templateKey", widget: hidden, default: "product"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: hidden, default: "gallery"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Upload Date", name: "uploadDate", widget: "datetime"}

  - name: "sections"
    label: "Sections"
    files:
      - file: "content/pages/services.md"
        label: "Services"
        name: "services"
        fields:
          - {label: "Key", name: "key", widget: "hidden", default: "services"}
          - {label: "Services Content", name: "body", widget: "markdown"}